# Generated by Django 4.1.1 on 2022-09-17 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='', max_length=70)),
                ('description', models.TextField(default='', max_length=500)),
                ('image', models.TextField(default='')),
                ('category_choice', models.CharField(choices=[('Education', 'Education'), ('Inspiration', 'Inspiration'), ('FICTION', 'Fiction')], default='SPORTS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenting_date', models.DateTimeField()),
                ('comment', models.TextField(default='', max_length=1000)),
                ('commenter', models.CharField(default='', max_length=50)),
                ('article', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment_on_article', to='hobeapp.article')),
            ],
        ),
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=100)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Inspiration', 'Inspiration'), ('FICTION', 'Fiction')], default='EDUCATION', max_length=20)),
                ('cover', models.ImageField(default='default.jpg', upload_to='story_cover')),
                ('story', models.TextField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=25)),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('username', models.CharField(default='', max_length=15)),
                ('password', models.CharField(default='', max_length=15)),
                ('confirm_password', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField()),
                ('category_choice', models.CharField(choices=[('Education', 'Education'), ('Inspiration', 'Inspiration'), ('FICTION', 'Fiction')], default='SPORTS', max_length=20)),
                ('reader_comment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Reader_comment', to='hobeapp.comment')),
                ('story_cover', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Story_cover', to='hobeapp.create')),
                ('story_publisher_username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Story_publisher_username', to='hobeapp.user')),
                ('story_title', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Story_title', to='hobeapp.create')),
                ('story_update', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Story_Update', to='hobeapp.create')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hobeapp.user'),
        ),
    ]
