# Generated by Django 4.1.1 on 2022-09-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25, null=True)),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('username', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
