# Generated by Django 4.1.1 on 2022-09-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_profile_picture', to='hobeapp.user')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_username', to='hobeapp.user')),
            ],
        ),
    ]
