# Generated by Django 4.1.1 on 2022-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category_choice',
            field=models.CharField(choices=[('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Geography', 'Geography'), ('Physics', 'Physics'), ('Maths', 'Maths')], default='SPORTS', max_length=20),
        ),
        migrations.AlterField(
            model_name='create',
            name='category',
            field=models.CharField(choices=[('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Geography', 'Geography'), ('Physics', 'Physics'), ('Maths', 'Maths')], default='CHEMISTRY', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='category_choice',
            field=models.CharField(choices=[('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Geography', 'Geography'), ('Physics', 'Physics'), ('Maths', 'Maths')], default='SPORTS', max_length=20),
        ),
    ]
