# Generated by Django 4.1.1 on 2022-09-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobeapp', '0002_alter_user_username_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('cover', models.ImageField(default='default.jpg', upload_to='story_cover')),
                ('story', models.TextField(max_length=2000)),
                ('publisher_profile_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publisher_profile_picture', to='hobeapp.user')),
                ('publisher_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publisher_username', to='hobeapp.user')),
            ],
        ),
    ]
