# Generated by Django 4.1.1 on 2022-09-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobeapp', '0003_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenting_date', models.DateTimeField()),
                ('comment', models.TextField(max_length=1000)),
                ('commenter_profile_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenter_profile_picture', to='hobeapp.user')),
                ('commenter_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenter_username', to='hobeapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField()),
                ('likes', models.IntegerField()),
                ('reader_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reader_comment', to='hobeapp.comment')),
                ('story_cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Story_cover', to='hobeapp.create')),
                ('story_publisher_profile_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Story_publisher_profile_picture', to='hobeapp.user')),
                ('story_publisher_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Story_publisher_username', to='hobeapp.user')),
                ('story_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Story_title', to='hobeapp.create')),
                ('story_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Story_Update', to='hobeapp.create')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_profile_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Like_profile_picture', to='hobeapp.user')),
                ('like_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Like_username', to='hobeapp.user')),
            ],
        ),
    ]
