# Generated by Django 4.1.1 on 2022-09-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobeapp', '0004_comment_story_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_profile_picture',
            new_name='commenter_picture',
        ),
    ]
