# Generated by Django 4.1.1 on 2022-09-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobeapp', '0005_rename_commenter_profile_picture_comment_commenter_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sp'), ('Entertainment', 'En'), ('Politics', 'Po')], default='SP', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='category_choice',
            field=models.CharField(choices=[('Sports', 'Sp'), ('Entertainment', 'En'), ('Politics', 'Po')], default='SP', max_length=20),
        ),
    ]
