# Generated by Django 4.1.1 on 2022-09-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobeapp', '0006_create_category_story_category_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics')], default='SPORTS', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='category_choice',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics')], default='SPORTS', max_length=20),
        ),
    ]
